# Run SwiftLint
START_DATE=$(date +"%s")

echo `pwd`
SWIFT_LINT=./Pods/SwiftLint/swiftlint

# Run SwiftLint for given filename
run_swiftlint() {
    local filename="${1}"

    # Ignore Pods and Vendor paths.
    [[ ${filename} =~ Pods/ ]] && return 0
    [[ ${filename} =~ Vendor/ ]] && return 0

    # Ignore autogenerated SwiftGen files.
    [[ ${filename} =~ .*SwiftGen\.swift ]] && return 0

    # Ignore templates and generated files.
    [[ ${filename} =~ .*Generated.* ]] && return 0

    # Only lint .swift files.
    ! [[ ${filename##*.} == "swift" ]] && return 0

    # Run the checks.
#    ${SWIFT_LINT} autocorrect --path "${filename}"
    ${SWIFT_LINT} lint --strict --path "${filename}"
}

if [[ -e "${SWIFT_LINT}" ]]; then
    echo "SwiftLint version: $(${SWIFT_LINT} version)"
    # Run for both staged and unstaged files
    git diff --name-only | while read filename; do run_swiftlint "${filename}"; done
    git diff --cached --name-only | while read filename; do run_swiftlint "${filename}"; done
else
    echo "${SWIFT_LINT} is not installed."
    exit 0
fi

END_DATE=$(date +"%s")

DIFF=$(($END_DATE - $START_DATE))
echo "SwiftLint took $(($DIFF / 60)) minutes and $(($DIFF % 60)) seconds to complete."
